"""
ARA Pipeline - Core Data Models
Adaptive Reasoning Architecture v2.0
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, TYPE_CHECKING
from datetime import datetime
from pathlib import Path

if TYPE_CHECKING:
    from core.protocol import PhaseResult


class TaskType(str, Enum):
    ANALYTICAL = "analytical"
    STRATEGIC = "strategic"
    CREATIVE = "creative"
    TECHNICAL = "technical"
    HYBRID = "hybrid"


class ClaimLabel(str, Enum):
    VERIFIED = "VERIFIED"
    HYPOTHESIS = "HYPOTHESIS"
    UNKNOWN = "UNKNOWN"


class ModelProvider(str, Enum):
    ANTHROPIC  = "anthropic"
    OPENAI     = "openai"
    GOOGLE     = "google"
    XAI        = "xai"
    PERPLEXITY = "perplexity"
    MISTRAL    = "mistral"
    DEEPSEEK   = "deepseek"
    QWEN       = "qwen"
    KIMI       = "kimi"
    GLM        = "glm"
    MINIMAX    = "minimax"


class PerspectiveType(str, Enum):
    CONSTRUCTIVE = "constructive"
    DESTRUCTIVE = "destructive"
    SYSTEMIC = "systemic"
    MINIMALIST = "minimalist"


class ScenarioType(str, Enum):
    OPTIMAL = "optimal"
    CONSTRAINT_VIOLATION = "constraint_violation"
    ADVERSARIAL = "adversarial"

    @classmethod
    def coerce(cls, value: str | "ScenarioType") -> "ScenarioType":
        """Accept enum values, enum names, and common separator variants."""
        if isinstance(value, cls):
            return value
        raw = str(value).strip()
        try:
            return cls(raw)
        except ValueError:
            normalized = raw.lower().replace("-", "_").replace(" ", "_")
            member = cls.__members__.get(normalized.upper())
            if member is not None:
                return member
            return cls(normalized)


@dataclass
class SubProblem:
    id: str
    description: str
    inputs: list[str]
    outputs: list[str]
    constraints: list[str]


@dataclass
class Assumption:
    text: str
    label: ClaimLabel
    rationale: str


@dataclass
class Decomposition:
    sub_problems: list[SubProblem]
    assumptions: list[Assumption]
    failure_modes: list[str]
    raw_response: str


@dataclass
class SolutionCandidate:
    perspective: PerspectiveType
    content: str
    key_insights: list[str]
    model_used: str


@dataclass
class CritiqueScore:
    perspective: PerspectiveType
    logical_consistency: float       # 0-10
    evidence_support: float          # 0-10
    failure_resilience: float        # 0-10
    feasibility: float               # 0-10
    bias_flags: list[str]
    steel_man: str                   # strongest counter-argument
    # Penalises overconfident-but-wrong claims; sourced from the critique prompt.
    # Default 0.0 so deserialized CritiqueScores without this field still load cleanly.
    confidence_vs_accuracy_penalty: float = 0.0

    @property
    def total(self) -> float:
        return (
            self.logical_consistency
            + self.evidence_support
            + self.failure_resilience
            + self.feasibility
        ) / 4.0


@dataclass
class StressTestResult:
    scenario: ScenarioType
    survival_rate: float             # 0.0 - 1.0
    failure_mode: str = ""
    recovery_path: str = ""


@dataclass
class MetaCognitiveAudit:
    most_dangerous_assumption: str
    dominant_bias: str
    remaining_uncertainty: str
    assumption_failure_impact: str
    non_obvious_insight: str


@dataclass
class GenerationCandidate:
    """A candidate solution generated by one of the 3 independent generators."""
    generator_id: str         # "generator_1", "generator_2", "generator_3"
    model_used: str           # actual model name
    solution: str             # full solution text
    confidence: float         # 0.0-1.0 self-assessed
    key_claims: list[str]     # verifiable claims
    approach_summary: str     # 1-2 sentence summary


@dataclass
class CriticDimensionScore:
    """Score for one candidate across one critic's 4 dimensions."""
    factuality: float         # 0-10
    reasoning: float          # 0-10
    completeness: float       # 0-10
    helpfulness: float        # 0-10

    @property
    def total(self) -> float:
        return (self.factuality + self.reasoning + self.completeness + self.helpfulness) / 4.0


@dataclass
class CriticScore:
    """Scores from one critic evaluating all 3 generator candidates."""
    critic_id: str            # "critic_1", "critic_2", "critic_3"
    critic_model: str
    candidate_scores: dict[str, CriticDimensionScore]  # generator_id → scores
    ranking: list[str]        # generator_ids best→worst
    dissenting_note: str


@dataclass
class VerificationResult:
    """Result of verifying a claim from a generator."""
    claim: str
    source_generator: str
    verdict: ClaimLabel       # VERIFIED / HYPOTHESIS / UNKNOWN
    evidence: str
    confidence: float         # 0.0-1.0


@dataclass
class MetaEvaluation:
    """Meta-evaluation of the critics themselves (judge-the-judges)."""
    critic_reliability: dict[str, float]  # critic_id → reliability 0-10
    bias_analysis: dict[str, str]         # critic_id → bias description
    agreement_rate: float                  # 0.0-1.0
    most_reliable_critic: str
    least_reliable_critic: str
    meta_insight: str


@dataclass
class FinalSolution:
    core_solution: str
    critical_insights: list[str]     # max 5, non-obvious only
    action_blueprint: list[dict[str, Any]]
    open_questions: list[str]
    claim_labels: dict[str, ClaimLabel]
    meta_audit: MetaCognitiveAudit
    sources: list[dict[str, str]] = field(default_factory=list)  # Citation sources: [{"title": "...", "url": "..."}]
    # ORCHESTRATED method fields
    generator_attribution: dict[str, str] = field(default_factory=dict)  # generator_id → contribution summary
    critic_weighting: dict[str, float] = field(default_factory=dict)  # critic_id → weight based on reliability


@dataclass
class PipelineState:
    """Complete pipeline state — passed between phases."""
    problem: str
    started_at: "datetime" = field(default_factory=datetime.now)
    task_type: TaskType | None = None
    task_type_rationale: str = ""
    language: str = "English"  # Detected language from the problem
    decomposition: Decomposition | None = None
    candidates: list[SolutionCandidate] = field(default_factory=list)
    scores: list[CritiqueScore] = field(default_factory=list)
    top_candidates: list[SolutionCandidate] = field(default_factory=list)
    stress_results: list[StressTestResult] = field(default_factory=list)
    final_solution: FinalSolution | None = None
    phase_logs: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    # Tracks which model was used for each phase role
    phase_models: dict[str, str] = field(default_factory=dict)
    # Tracks tokens used per phase: {phase_name: {"input": int, "output": int}}
    phase_tokens: dict[str, dict[str, int]] = field(default_factory=dict)
    # Immutable per-phase results (foundation for future resume/replay support)
    phase_results: list["PhaseResult"] = field(default_factory=list)
    # Which preset was used — drives method-specific rendering
    preset_name: str | None = None
    # ORCHESTRATED method fields (populated only when preset is orchestrated)
    generation_candidates: list["GenerationCandidate"] = field(default_factory=list)
    critic_scores: list["CriticScore"] = field(default_factory=list)
    verification_results: list["VerificationResult"] = field(default_factory=list)
    meta_evaluation: "MetaEvaluation | None" = None

    # ─────────────────────────────────────────────────────────────────────
    # NEW: Advanced Method States (v2.1)
    # ─────────────────────────────────────────────────────────────────────
    # Iterative Method: Stores previous failure analysis to guide next loop
    reflexion_memory: list[str] = field(default_factory=list)
    # Jury Method: Constitution/Principles defined in Phase 1 for objective scoring
    jury_guidelines: list[str] = field(default_factory=list)
    # Debate Method: Structured rounds (opening, rebuttal, cross-exam)
    debate_rounds: list[dict[str, Any]] = field(default_factory=list)
    # Scientific Method: Hypotheses, experiments, and falsification tests
    scientific_state: dict[str, Any] = field(default_factory=dict)
    # Socratic Method: Definitions, questions (elenchus), and aporia state
    socratic_state: dict[str, Any] = field(default_factory=dict)
    # Web Discovery: Results from SearXNG search
    web_discovery_results: list[dict[str, Any]] = field(default_factory=list)
    # Vetted Context: Flags from context vetting phase
    vetted_context: list[dict[str, Any]] = field(default_factory=list)

    def log(self, phase: str, message: str) -> None:
        entry = f"[{phase}] {message}"
        self.phase_logs.append(entry)

    def to_context_dict(self) -> dict[str, Any]:
        """Serialize state for passing to next LLM call."""
        return {
            "problem": self.problem,
            "task_type": self.task_type.value if self.task_type else None,
            "language": self.language,
            "reflexion_memory": self.reflexion_memory,
            "jury_guidelines": self.jury_guidelines,
            "debate_rounds": self.debate_rounds,
            "scientific_state": self.scientific_state,
            "socratic_state": self.socratic_state,
            "web_discovery_results": self.web_discovery_results,
            "sub_problems": [
                {
                    "id": sp.id,
                    "description": sp.description,
                    "inputs": sp.inputs,
                    "outputs": sp.outputs,
                    "constraints": sp.constraints,
                }
                for sp in (self.decomposition.sub_problems if self.decomposition else [])
            ],
            "assumptions": [
                {"text": a.text, "label": a.label.value}
                for a in (self.decomposition.assumptions if self.decomposition else [])
            ],
            "candidates": [
                {
                    "perspective": c.perspective.value,
                    "content": c.content[:800],  # truncate for context efficiency
                    "key_insights": c.key_insights,
                }
                for c in self.top_candidates or self.candidates
            ],
            "scores": [
                {
                    "perspective": s.perspective.value,
                    "total": round(s.total, 2),
                    "bias_flags": s.bias_flags,
                }
                for s in self.scores
            ],
            "stress_results": [
                {
                    "scenario": sr.scenario.value,
                    "survival_rate": sr.survival_rate,
                    "failure_mode": sr.failure_mode,
                    "recovery_path": sr.recovery_path,
                }
                for sr in self.stress_results
            ],
            # ORCHESTRATED method context (empty for other methods)
            "generation_candidates": [
                {
                    "generator_id": gc.generator_id,
                    "model_used": gc.model_used,
                    "solution": gc.solution[:1000],
                    "confidence": gc.confidence,
                    "key_claims": gc.key_claims,
                    "approach_summary": gc.approach_summary,
                }
                for gc in self.generation_candidates
            ],
            "critic_scores": [
                {
                    "critic_id": cs.critic_id,
                    "critic_model": cs.critic_model,
                    "candidate_scores": {
                        gen_id: {
                            "factuality": ds.factuality,
                            "reasoning": ds.reasoning,
                            "completeness": ds.completeness,
                            "helpfulness": ds.helpfulness,
                            "total": round(ds.total, 2),
                        }
                        for gen_id, ds in cs.candidate_scores.items()
                    },
                    "ranking": cs.ranking,
                }
                for cs in self.critic_scores
            ],
            "verification_results": [
                {
                    "claim": vr.claim,
                    "source_generator": vr.source_generator,
                    "verdict": vr.verdict.value,
                    "evidence": vr.evidence,
                    "confidence": vr.confidence,
                }
                for vr in self.verification_results
            ],
        }

    def to_dict(self) -> dict[str, Any]:
        """Serialize complete state to dictionary (for persistence)."""
        def serialize(obj: Any) -> Any:
            if isinstance(obj, Enum):
                return obj.value
            if isinstance(obj, datetime):
                return obj.isoformat()
            if isinstance(obj, list):
                return [serialize(item) for item in obj]
            if isinstance(obj, dict):
                return {k: serialize(v) for k, v in obj.items()}
            if hasattr(obj, '__dataclass_fields__'):
                return {k: serialize(v) for k, v in asdict(obj).items()}
            return obj
        
        return serialize(asdict(self))

    def save(self, path: str | Path) -> None:
        """Save state to JSON file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(self.to_dict(), f, indent=2, ensure_ascii=False)

    @classmethod
    def load(cls, path: str | Path) -> "PipelineState":
        """Load state from JSON file."""
        path = Path(path)
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # Reconstruct enums and complex types
        return cls._from_dict(data)

    @classmethod
    def _from_dict(cls, data: dict[str, Any]) -> "PipelineState":
        """Deserialize dictionary to PipelineState with proper type reconstruction."""
        # Convert string enums back to Enum types
        if data.get('task_type'):
            data['task_type'] = TaskType(data['task_type'])
        if data.get('started_at'):
            data['started_at'] = datetime.fromisoformat(data['started_at'])
        
        # Reconstruct decomposition
        if data.get('decomposition'):
            dec = data['decomposition']
            dec['sub_problems'] = [SubProblem(**sp) for sp in dec.get('sub_problems', [])]
            dec['assumptions'] = [
                Assumption(
                    text=a['text'],
                    label=ClaimLabel(a['label']),
                    rationale=a['rationale']
                ) for a in dec.get('assumptions', [])
            ]
            data['decomposition'] = Decomposition(**dec)
        
        # Reconstruct candidates with PerspectiveType
        if data.get('candidates'):
            data['candidates'] = [
                SolutionCandidate(
                    perspective=PerspectiveType(c['perspective']),
                    content=c['content'],
                    key_insights=c['key_insights'],
                    model_used=c['model_used']
                ) for c in data['candidates']
            ]
        
        # Reconstruct scores with PerspectiveType
        if data.get('scores'):
            data['scores'] = [
                CritiqueScore(
                    perspective=PerspectiveType(s['perspective']),
                    logical_consistency=s['logical_consistency'],
                    evidence_support=s['evidence_support'],
                    failure_resilience=s['failure_resilience'],
                    feasibility=s['feasibility'],
                    bias_flags=s['bias_flags'],
                    steel_man=s['steel_man']
                ) for s in data['scores']
            ]
        
        # Reconstruct top_candidates
        if data.get('top_candidates'):
            data['top_candidates'] = [
                SolutionCandidate(
                    perspective=PerspectiveType(c['perspective']),
                    content=c['content'],
                    key_insights=c['key_insights'],
                    model_used=c['model_used']
                ) for c in data['top_candidates']
            ]
        
        # Reconstruct stress_results with ScenarioType
        if data.get('stress_results'):
            data['stress_results'] = [
                StressTestResult(
                    scenario=ScenarioType.coerce(sr['scenario']),
                    survival_rate=sr['survival_rate'],
                    failure_mode=sr['failure_mode'],
                    recovery_path=sr['recovery_path']
                ) for sr in data['stress_results']
            ]
        
        # Reconstruct final_solution with ClaimLabel and MetaCognitiveAudit
        if data.get('final_solution'):
            fs = data['final_solution']
            # If it's already a FinalSolution object (unlikely here but for safety)
            if hasattr(fs, '__dataclass_fields__'):
                data['final_solution'] = fs
            else:
                # Ensure it's a dict
                fs_dict = fs if isinstance(fs, dict) else {}
                
                # Safely reconstruct meta_audit
                ma = fs_dict.get('meta_audit', {})
                if not isinstance(ma, dict): ma = {}
                meta_audit_obj = MetaCognitiveAudit(
                    most_dangerous_assumption=ma.get('most_dangerous_assumption', ''),
                    dominant_bias=ma.get('dominant_bias', ''),
                    remaining_uncertainty=ma.get('remaining_uncertainty', ''),
                    assumption_failure_impact=ma.get('assumption_failure_impact', ''),
                    non_obvious_insight=ma.get('non_obvious_insight', '')
                )
                
                # Safely reconstruct claim_labels
                raw_labels = fs_dict.get('claim_labels', {})
                if not isinstance(raw_labels, dict): raw_labels = {}
                clean_labels = {}
                for k, v in raw_labels.items():
                    try:
                        clean_labels[k] = ClaimLabel(v)
                    except ValueError:
                        clean_labels[k] = ClaimLabel.UNKNOWN

                data['final_solution'] = FinalSolution(
                    core_solution=fs_dict.get('core_solution', ''),
                    critical_insights=fs_dict.get('critical_insights', []),
                    action_blueprint=fs_dict.get('action_blueprint', []),
                    open_questions=fs_dict.get('open_questions', []),
                    claim_labels=clean_labels,
                    meta_audit=meta_audit_obj,
                    sources=fs_dict.get('sources', []),
                    generator_attribution=fs_dict.get('generator_attribution', {}),
                    critic_weighting=fs_dict.get('critic_weighting', {})
                )
        
        # Reconstruct generation_candidates
        if data.get('generation_candidates'):
            data['generation_candidates'] = [
                GenerationCandidate(**gc) for gc in data['generation_candidates']
            ]
        
        # Reconstruct critic_scores
        if data.get('critic_scores'):
            new_scores = []
            for cs in data['critic_scores']:
                cs['candidate_scores'] = {
                    k: CriticDimensionScore(**v) for k, v in cs['candidate_scores'].items()
                }
                new_scores.append(CriticScore(**cs))
            data['critic_scores'] = new_scores
        
        # Reconstruct verification_results with ClaimLabel
        if data.get('verification_results'):
            data['verification_results'] = [
                VerificationResult(
                    claim=vr['claim'],
                    source_generator=vr['source_generator'],
                    verdict=ClaimLabel(vr['verdict']),
                    evidence=vr['evidence'],
                    confidence=vr['confidence']
                ) for vr in data['verification_results']
            ]
        
        # Reconstruct meta_evaluation
        if data.get('meta_evaluation'):
            data['meta_evaluation'] = MetaEvaluation(**data['meta_evaluation'])
        
        return cls(**data)
