"""
ARA Pipeline - Core Data Models
Adaptive Reasoning Architecture v2.0
"""

from __future__ import annotations

import json
from collections import deque
from dataclasses import dataclass, field, asdict, fields as dc_fields
from enum import Enum
from typing import Any, TYPE_CHECKING
from datetime import datetime
from pathlib import Path

if TYPE_CHECKING:
    from reasoner.core.protocol import PhaseResult


class TaskType(str, Enum):
    ANALYTICAL = "analytical"
    STRATEGIC = "strategic"
    CREATIVE = "creative"
    TECHNICAL = "technical"
    PREDICTIVE = "predictive"
    HYBRID = "hybrid"


class ClaimLabel(str, Enum):
    VERIFIED = "VERIFIED"
    HYPOTHESIS = "HYPOTHESIS"
    UNKNOWN = "UNKNOWN"


class ModelProvider(str, Enum):
    ANTHROPIC  = "anthropic"
    OPENAI     = "openai"
    GOOGLE     = "google"
    XAI        = "xai"
    PERPLEXITY = "perplexity"
    MISTRAL    = "mistral"
    DEEPSEEK   = "deepseek"
    QWEN       = "qwen"
    KIMI       = "kimi"
    GLM        = "glm"
    MINIMAX    = "minimax"


class PerspectiveType(str, Enum):
    CONSTRUCTIVE = "constructive"
    DESTRUCTIVE = "destructive"
    SYSTEMIC = "systemic"
    MINIMALIST = "minimalist"


class ScenarioType(str, Enum):
    OPTIMAL = "optimal"
    CONSTRAINT_VIOLATION = "constraint_violation"
    ADVERSARIAL = "adversarial"

    @classmethod
    def coerce(cls, value: str | "ScenarioType") -> "ScenarioType":
        """Accept enum values, enum names, and common separator variants.
        Unknown scenario names returned by the LLM gracefully fall back to
        ADVERSARIAL so that stress-test results are not silently discarded.
        """
        if isinstance(value, cls):
            return value
        raw = str(value).strip()
        try:
            return cls(raw)
        except ValueError:
            normalized = raw.lower().replace("-", "_").replace(" ", "_")
            member = cls.__members__.get(normalized.upper())
            if member is not None:
                return member
            return cls.ADVERSARIAL


@dataclass
class SubProblem:
    id: str
    description: str
    inputs: list[str]
    outputs: list[str]
    constraints: list[str]


@dataclass
class Assumption:
    text: str
    label: ClaimLabel
    rationale: str = ""
    source_hint: str = ""


@dataclass
class Decomposition:
    sub_problems: list[SubProblem]
    assumptions: list[Assumption]
    failure_modes: list[str]
    # raw_response is only populated when explicitly saved by the pipeline.
    # Default "" so _from_dict can filter unknown LLM keys without crashing.
    raw_response: str = ""
    critical_sources: list[dict[str, str]] = field(default_factory=list)


@dataclass
class SolutionCandidate:
    perspective: PerspectiveType
    content: str
    key_insights: list[str]
    model_used: str


@dataclass
class CritiqueScore:
    perspective: PerspectiveType
    logical_consistency: float       # 0-10
    evidence_support: float          # 0-10
    failure_resilience: float        # 0-10
    feasibility: float               # 0-10
    bias_flags: list[str]
    steel_man: str                   # strongest counter-argument
    # Penalises overconfident-but-wrong claims; sourced from the critique prompt.
    # Default 0.0 so deserialized CritiqueScores without this field still load cleanly.
    confidence_vs_accuracy_penalty: float = 0.0

    @property
    def total(self) -> float:
        base = (
            self.logical_consistency
            + self.evidence_support
            + self.failure_resilience
            + self.feasibility
        ) / 4.0
        return max(0.0, base - self.confidence_vs_accuracy_penalty)


@dataclass
class StressTestResult:
    scenario: ScenarioType
    survival_rate: float             # 0.0 - 1.0
    failure_mode: str = ""
    recovery_path: str = ""


@dataclass
class MetaCognitiveAudit:
    most_dangerous_assumption: str
    dominant_bias: str
    remaining_uncertainty: str
    assumption_failure_impact: str
    non_obvious_insight: str


@dataclass
class GenerationCandidate:
    """A candidate solution generated by one of the 3 independent generators."""
    generator_id: str         # "generator_1", "generator_2", "generator_3"
    model_used: str           # actual model name
    solution: str             # full solution text
    confidence: float         # 0.0-1.0 self-assessed
    key_claims: list[str]     # verifiable claims
    approach_summary: str     # 1-2 sentence summary


@dataclass
class CriticDimensionScore:
    """Score for one candidate across one critic's 4 dimensions."""
    factuality: float         # 0-10
    reasoning: float          # 0-10
    completeness: float       # 0-10
    helpfulness: float        # 0-10

    @property
    def total(self) -> float:
        return (self.factuality + self.reasoning + self.completeness + self.helpfulness) / 4.0


@dataclass
class CriticScore:
    """Scores from one critic evaluating all 3 generator candidates."""
    critic_id: str            # "critic_1", "critic_2", "critic_3"
    critic_model: str
    candidate_scores: dict[str, CriticDimensionScore]  # generator_id → scores
    ranking: list[str]        # generator_ids best→worst
    dissenting_note: str


@dataclass
class VerificationResult:
    """Result of verifying a claim from a generator."""
    claim: str
    source_generator: str
    verdict: ClaimLabel       # VERIFIED / HYPOTHESIS / UNKNOWN
    evidence: str
    confidence: float         # 0.0-1.0


@dataclass
class MetaEvaluation:
    """Meta-evaluation of the critics themselves (judge-the-judges)."""
    critic_reliability: dict[str, float]  # critic_id → reliability 0-10
    bias_analysis: dict[str, str]         # critic_id → bias description
    agreement_rate: float                  # 0.0-1.0
    most_reliable_critic: str
    least_reliable_critic: str
    meta_insight: str


@dataclass
class FinalSolution:
    core_solution: str
    critical_insights: list[str]     # max 5, non-obvious only
    action_blueprint: list[dict[str, Any]]
    open_questions: list[str]
    claim_labels: dict[str, ClaimLabel]
    meta_audit: MetaCognitiveAudit
    sources: list[dict[str, str]] = field(default_factory=list)  # Citation sources: [{"title": "...", "url": "..."}]
    # ORCHESTRATED method fields
    generator_attribution: dict[str, str] = field(default_factory=dict)  # generator_id → contribution summary
    critic_weighting: dict[str, float] = field(default_factory=dict)  # critic_id → weight based on reliability


@dataclass
class PipelineState:
    """Complete pipeline state — passed between phases."""
    problem: str
    enhanced_problem: str = ""  # Auto-rewritten prompt for clarity and context
    started_at: "datetime" = field(default_factory=datetime.now)
    task_type: TaskType | None = None
    task_type_rationale: str = ""
    language: str = "English"  # Detected language from the problem
    decomposition: Decomposition | None = None
    candidates: list[SolutionCandidate] = field(default_factory=list)
    scores: list[CritiqueScore] = field(default_factory=list)
    top_candidates: list[SolutionCandidate] = field(default_factory=list)
    stress_results: list[StressTestResult] = field(default_factory=list)
    final_solution: FinalSolution | None = None
    phase_logs: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    # Tracks which model was used for each phase role
    phase_models: dict[str, str] = field(default_factory=dict)
    # Tracks tokens used per phase: {phase_name: {"input": int, "output": int}}
    phase_tokens: dict[str, dict[str, int]] = field(default_factory=dict)
    # Tracks duration (seconds) per phase: {phase_name: float}
    phase_durations: dict[str, float] = field(default_factory=dict)
    # Immutable per-phase results (foundation for future resume/replay support)
    phase_results: list["PhaseResult"] = field(default_factory=list)
    # Which preset was used — drives method-specific rendering
    preset_name: str | None = None
    # ORCHESTRATED method fields (populated only when preset is orchestrated)
    generation_candidates: list["GenerationCandidate"] = field(default_factory=list)
    critic_scores: list["CriticScore"] = field(default_factory=list)
    verification_results: list["VerificationResult"] = field(default_factory=list)
    meta_evaluation: "MetaEvaluation | None" = None

    # ─────────────────────────────────────────────────────────────────────
    # NEW: Advanced Method States (v2.1)
    # ─────────────────────────────────────────────────────────────────────
    # Iterative Method: Stores previous failure analysis to guide next loop
    reflexion_memory: deque[str] = field(default_factory=lambda: deque(maxlen=50))
    # Jury Method: Constitution/Principles defined in Phase 1 for objective scoring
    jury_guidelines: list[str] = field(default_factory=list)
    # Debate Method: Structured rounds (opening, rebuttal, cross-exam)
    debate_rounds: list[dict[str, Any]] = field(default_factory=list)
    # Scientific Method: Hypotheses, experiments, and falsification tests
    scientific_state: dict[str, Any] = field(default_factory=dict)
    # Socratic Method: Definitions, questions (elenchus), and aporia state
    socratic_state: dict[str, Any] = field(default_factory=dict)
    # Jury Method: Reliability-weighted generator ranking (Track A3)
    jury_weighted_ranking: list[str] = field(default_factory=list)
    # Pre-Mortem Analysis Method: Prospective hindsight failure analysis (B1)
    pre_mortem_state: dict[str, Any] = field(default_factory=dict)
    # Bayesian Reasoning Method: Prior-likelihood-posterior-sensitivity (B2)
    bayesian_state: dict[str, Any] = field(default_factory=dict)
    # Dialectical Reasoning Method: Hegelian Aufhebung (B3)
    dialectical_state: dict[str, Any] = field(default_factory=dict)
    # Analogical Reasoning Method: Structure-mapping & cross-domain transfer (B4)
    analogical_state: dict[str, Any] = field(default_factory=dict)
    # Delphi Method: Expert consensus with convergence tracking (B5)
    delphi_state: dict[str, Any] = field(default_factory=dict)
    # Web Discovery: Results from SearXNG search
    web_discovery_results: list[dict[str, Any]] = field(default_factory=list)
    # Vetted Context: Flags from context vetting phase
    vetted_context: list[dict[str, Any]] = field(default_factory=list)
    
    # ─────────────────────────────────────────────────────────────────────
    # Cost Tracking (OpenRouter & Direct API)
    # ─────────────────────────────────────────────────────────────────────
    # Total cost in USD for the entire pipeline run
    total_cost_usd: float = 0.0
    # Per-phase cost breakdown: {phase_name: cost_in_usd}
    phase_costs: dict[str, float] = field(default_factory=dict)
    # Per-phase token usage: {phase_name: {"input": int, "output": int, "total": int}}
    # (supersedes phase_tokens which only tracked input/output)
    detailed_token_usage: dict[str, dict[str, int]] = field(default_factory=dict)

    # ─────────────────────────────────────────────────────────────────────
    # Conversation Context (Multi-turn Follow-up Support)
    # ─────────────────────────────────────────────────────────────────────
    conversation_history: list[dict[str, str]] = field(default_factory=list)
    conversation_id: str = ""
    turn_number: int = 1
    previous_synthesis: str = ""
    agent_model: str | None = None  # Tier-based agent override for follow-ups

    def log(self, phase: str, message: str) -> None:
        entry = f"[{phase}] {message}"
        self.phase_logs.append(entry)

    def to_context_dict(self, phase: str = "default", compression: str = "balanced", use_neuro: bool = False) -> dict[str, Any]:
        """
        Serialize state for passing to next LLM call.
        
        Args:
            phase: Current phase name (determines what data to include)
            compression: Compression level - "aggressive" | "balanced" | "none"
            use_neuro: If True, use neuro-compression for text content (40-50% additional savings)
        
        Returns:
            Context dictionary optimized for token efficiency
        """
        # Base context - always included
        context = {
            "problem": self.problem,
            "task_type": (self.task_type.value if hasattr(self.task_type, 'value') else self.task_type) if self.task_type else None,
            "language": self.language,
        }
        
        from reasoner.core.constants import TRUNCATION
        # Aggressive compression: minimal context
        if compression == "aggressive":
            context["problem"] = self.problem[:TRUNCATION.PROBLEM]  # Truncate problem
            # Only include phase-relevant data
            if phase in ["perspective", "constructive", "destructive", "systemic", "minimalist"]:
                context["decomposition_summary"] = self._get_decomposition_summary()
            elif phase in ["scoring", "critique"]:
                context["candidates_summary"] = self._get_candidates_summary(max_candidates=3, max_chars=200)
            elif phase in ["stress_testing"]:
                context["top_candidates_summary"] = self._get_candidates_summary(max_candidates=2, max_chars=150)
            return context
        
        def _get_attr(obj: Any, key: str, default: Any = None) -> Any:
            if obj is None:
                return default
            if hasattr(obj, key):
                return getattr(obj, key, default)
            if isinstance(obj, dict):
                return obj.get(key, default)
            return default

        def _get_value(obj: Any) -> Any:
            return obj.value if hasattr(obj, "value") else obj

        # Balanced compression (default) - progressive truncation
        context.update({
            "reflexion_memory": list(self.reflexion_memory),
            "jury_guidelines": self.jury_guidelines,
            "debate_rounds": self.debate_rounds,
            "scientific_state": self.scientific_state,
            "socratic_state": self.socratic_state,
            "jury_weighted_ranking": self.jury_weighted_ranking,
            "pre_mortem_state": self.pre_mortem_state,
            "bayesian_state": self.bayesian_state,
            "dialectical_state": self.dialectical_state,
            "analogical_state": self.analogical_state,
            "delphi_state": self.delphi_state,
            "web_discovery_results": self.web_discovery_results,
            "sub_problems": [
                {
                    "id": _get_attr(sp, "id"),
                    "description": (_get_attr(sp, "description", "")[:TRUNCATION.API_STORAGE] if use_neuro else _get_attr(sp, "description", "")),
                    "inputs": _get_attr(sp, "inputs", []),
                    "outputs": _get_attr(sp, "outputs", []),
                    "constraints": _get_attr(sp, "constraints", []),
                }
                for sp in (_get_attr(self.decomposition, "sub_problems", []) if self.decomposition else [])
            ],
            "assumptions": [
                {"text": (_get_attr(a, "text", "")[:TRUNCATION.ASSUMPTION] if use_neuro else _get_attr(a, "text", "")), "label": _get_value(_get_attr(a, "label", ClaimLabel.UNKNOWN))}
                for a in (_get_attr(self.decomposition, "assumptions", []) if self.decomposition else [])
            ],
            "candidates": [
                {
                    "perspective": _get_value(_get_attr(c, "perspective")),
                    "content": _get_attr(c, "content", "")[:TRUNCATION.CONTENT],
                    "key_insights": (_get_attr(c, "key_insights", [])[:TRUNCATION.KEY_INSIGHTS] if use_neuro else _get_attr(c, "key_insights", [])),
                }
                for c in self.top_candidates or self.candidates
            ],
            "scores": [
                {
                    "perspective": _get_value(_get_attr(s, "perspective")),
                    "total": round(_get_attr(s, "total", 0), 2),
                    "bias_flags": _get_attr(s, "bias_flags", []),
                }
                for s in self.scores
            ],
            "stress_results": [
                {
                    "scenario": _get_value(_get_attr(sr, "scenario")),
                    "survival_rate": _get_attr(sr, "survival_rate", 0),
                    "failure_mode": (_get_attr(sr, "failure_mode", "")[:TRUNCATION.SESSION_EXCERPT] if use_neuro else _get_attr(sr, "failure_mode", "")),
                    "recovery_path": (_get_attr(sr, "recovery_path", "")[:TRUNCATION.SESSION_EXCERPT] if use_neuro else _get_attr(sr, "recovery_path", "")),
                }
                for sr in self.stress_results
            ],
        })
        
        # ORCHESTRATED method context (empty for other methods)
        context.update({
            "generation_candidates": [
                {
                    "generator_id": gc.generator_id,
                    "model_used": gc.model_used,
                    "solution": gc.solution[:TRUNCATION.SOLUTION],
                    "confidence": gc.confidence,
                    "key_claims": gc.key_claims[:TRUNCATION.KEY_INSIGHTS] if use_neuro else gc.key_claims,
                    "approach_summary": gc.approach_summary[:TRUNCATION.API_STORAGE] if use_neuro else gc.approach_summary,
                }
                for gc in self.generation_candidates
            ],
            "critic_scores": [
                {
                    "critic_id": cs.critic_id,
                    "critic_model": cs.critic_model,
                    "candidate_scores": {
                        gen_id: {
                            "factuality": ds.factuality,
                            "reasoning": ds.reasoning,
                            "completeness": ds.completeness,
                            "helpfulness": ds.helpfulness,
                            "total": round(ds.total, 2),
                        }
                        for gen_id, ds in cs.candidate_scores.items()
                    },
                    "ranking": cs.ranking,
                    "dissenting_note": cs.dissenting_note[:TRUNCATION.SESSION_EXCERPT] if use_neuro else cs.dissenting_note,
                }
                for cs in self.critic_scores
            ],
            "verification_results": [
                {
                    "claim": vr.claim[:TRUNCATION.API_STORAGE] if use_neuro else vr.claim,
                    "source_generator": vr.source_generator,
                    "verdict": vr.verdict.value,
                    "evidence": vr.evidence[:TRUNCATION.API_STORAGE] if use_neuro else vr.evidence,
                    "confidence": vr.confidence,
                }
                for vr in self.verification_results
            ],
        })
        
        return context
    
    def _get_decomposition_summary(self) -> dict[str, Any]:
        """Get condensed decomposition summary for token efficiency."""
        if not self.decomposition:
            return {}
        return {
            "causal_chain_length": len(self.decomposition.sub_problems) if hasattr(self.decomposition, 'sub_problems') else 0,
            "key_assumptions": [
                {"text": a.text[:TRUNCATION.SESSION_EXCERPT], "label": a.label.value}
                for a in (self.decomposition.assumptions[:TRUNCATION.KEY_INSIGHTS] if self.decomposition.assumptions else [])
            ],
        }
    
    def _get_candidates_summary(self, max_candidates: int = 3, max_chars: int = 200) -> list[dict]:
        """Get condensed candidates summary for token efficiency."""
        candidates = self.top_candidates or self.candidates
        return [
            {
                "perspective": c.perspective.value,
                "one_liner": c.content[:max_chars],
                "key_insights": c.key_insights[:TRUNCATION.MEMORY],  # Top 2 only
            }
            for c in candidates[:max_candidates]
        ]

    def to_dict(self) -> dict[str, Any]:
        """Serialize complete state to dictionary (for persistence)."""
        def serialize(obj: Any) -> Any:
            if isinstance(obj, Enum):
                return obj.value
            if isinstance(obj, datetime):
                return obj.isoformat()
            if isinstance(obj, deque):
                return list(obj)
            if isinstance(obj, list):
                return [serialize(item) for item in obj]
            if isinstance(obj, dict):
                return {k: serialize(v) for k, v in obj.items()}
            if hasattr(obj, '__dataclass_fields__'):
                return {k: serialize(v) for k, v in asdict(obj).items()}
            return obj
        
        return serialize(asdict(self))

    def save(self, path: str | Path) -> None:
        """
        Save state to JSON file.
        
        Args:
            path: File path to save to
            
        Raises:
            PermissionError: If write permission is denied
            OSError: If disk is full or path is invalid
            TypeError: If state contains non-serializable data
        """
        import logging
        logger = logging.getLogger(__name__)
        
        path = Path(path)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, 'w', encoding='utf-8') as f:
                json.dump(self.to_dict(), f, indent=2, ensure_ascii=False)
            logger.info(f"PipelineState saved to {path}")
        except PermissionError as e:
            logger.error(f"Permission denied saving PipelineState to {path}: {e}")
            raise
        except OSError as e:
            logger.error(f"OS error saving PipelineState to {path}: {e}")
            raise
        except TypeError as e:
            logger.error(f"Cannot serialize PipelineState: {e}")
            raise
        except Exception as e:
            logger.error(f"Unexpected error saving PipelineState to {path}: {e}")
            raise

    @classmethod
    def load(cls, path: str | Path) -> "PipelineState":
        """
        Load state from JSON file.
        
        Args:
            path: File path to load from
            
        Returns:
            Reconstructed PipelineState instance
            
        Raises:
            FileNotFoundError: If the file does not exist
            PermissionError: If read permission is denied
            json.JSONDecodeError: If the file contains invalid JSON
            ValueError: If the file is corrupted or incomplete
        """
        import logging
        logger = logging.getLogger(__name__)
        
        path = Path(path)
        try:
            if not path.exists():
                raise FileNotFoundError(f"PipelineState file not found: {path}")
            
            with open(path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            logger.info(f"PipelineState loaded from {path}")
            # Reconstruct enums and complex types
            return cls._from_dict(data)
        except FileNotFoundError:
            raise
        except PermissionError as e:
            logger.error(f"Permission denied loading PipelineState from {path}: {e}")
            raise
        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON in PipelineState file {path}: {e}")
            raise
        except Exception as e:
            logger.error(f"Unexpected error loading PipelineState from {path}: {e}")
            raise ValueError(f"Failed to load PipelineState: {e}") from e

    @classmethod
    def _from_dict(cls, data: dict[str, Any]) -> "PipelineState":
        """Deserialize dictionary to PipelineState with proper type reconstruction."""
        # Convert string enums back to Enum types
        if data.get('task_type'):
            data['task_type'] = TaskType(data['task_type'])
        if data.get('started_at'):
            data['started_at'] = datetime.fromisoformat(data['started_at'])
        
        # Reconstruct decomposition.
        # The LLM returns extra keys (causal_chain, critical_sources, …) that are
        # not in the Decomposition dataclass.  Strip unknown keys before unpacking
        # so that a saved state with any LLM-generated decomposition can be resumed.
        # CRITICAL: Use defensive .get() for ALL nested dataclasses to handle
        # truncated or corrupted state files gracefully.
        if data.get('decomposition'):
            dec = data['decomposition']
            # SubProblem reconstruction with error handling and type coercion
            _sub_problems = []
            for sp in dec.get('sub_problems', []):
                try:
                    # Coerce list fields to lists in case LLM returned wrong type
                    _inputs = sp.get('inputs', [])
                    if not isinstance(_inputs, list):
                        _inputs = [str(_inputs)] if _inputs else []
                    _outputs = sp.get('outputs', [])
                    if not isinstance(_outputs, list):
                        _outputs = [str(_outputs)] if _outputs else []
                    _constraints = sp.get('constraints', [])
                    if not isinstance(_constraints, list):
                        _constraints = [str(_constraints)] if _constraints else []
                    
                    _sub_problems.append(SubProblem(
                        id=str(sp.get('id', '')),
                        description=str(sp.get('description', '')),
                        inputs=_inputs,
                        outputs=_outputs,
                        constraints=_constraints,
                    ))
                except (TypeError, ValueError, KeyError):
                    pass  # skip malformed sub_problem entry
            dec['sub_problems'] = _sub_problems
            
            # Use .get() with fallbacks: a missing 'rationale' or 'label' key in a
            # saved assumption entry must not crash the entire resume.  Direct
            # subscript access caused KeyError for any partially-written state file.
            _assumptions = []
            for a in dec.get('assumptions', []):
                try:
                    _assumptions.append(Assumption(
                        text=str(a.get('text', '')),
                        label=ClaimLabel(str(a.get('label', ClaimLabel.UNKNOWN.value))),
                        rationale=str(a.get('rationale', '')),
                        source_hint=str(a.get('source_hint', '')),
                    ))
                except (ValueError, KeyError):
                    pass  # skip malformed assumption entry
            dec['assumptions'] = _assumptions

            # Preserve critical_sources if present
            _cs = dec.get('critical_sources', [])
            dec['critical_sources'] = [dict(cs) for cs in _cs if isinstance(cs, dict)]
            
            # Strip unknown keys before constructing Decomposition
            _known = {f.name for f in dc_fields(Decomposition)}
            data['decomposition'] = Decomposition(**{k: v for k, v in dec.items() if k in _known})
        
        # Reconstruct candidates with PerspectiveType
        if data.get('candidates'):
            data['candidates'] = [
                SolutionCandidate(
                    perspective=PerspectiveType(c['perspective']),
                    content=c['content'],
                    key_insights=c['key_insights'],
                    model_used=c['model_used']
                ) for c in data['candidates']
            ]
        
        # Reconstruct scores with PerspectiveType
        if data.get('scores'):
            data['scores'] = [
                CritiqueScore(
                    perspective=PerspectiveType(s['perspective']),
                    logical_consistency=s['logical_consistency'],
                    evidence_support=s['evidence_support'],
                    failure_resilience=s['failure_resilience'],
                    feasibility=s['feasibility'],
                    bias_flags=s['bias_flags'],
                    steel_man=s['steel_man']
                ) for s in data['scores']
            ]
        
        # Reconstruct top_candidates
        if data.get('top_candidates'):
            data['top_candidates'] = [
                SolutionCandidate(
                    perspective=PerspectiveType(c['perspective']),
                    content=c['content'],
                    key_insights=c['key_insights'],
                    model_used=c['model_used']
                ) for c in data['top_candidates']
            ]
        
        # Reconstruct stress_results with ScenarioType.
        # BUG-021: _from_dict used direct subscripts sr['scenario'] etc. — a
        # truncated or older state file missing any field crashed with KeyError.
        # Use .get() + coerce (matching the live-pipeline fix from BUG-015) and
        # skip malformed entries with a warning instead of crashing the load.
        if data.get('stress_results'):
            _stress_results: list[StressTestResult] = []
            for sr in data['stress_results']:
                try:
                    _stress_results.append(StressTestResult(
                        scenario=ScenarioType.coerce(sr.get('scenario', 'optimal')),
                        survival_rate=float(sr.get('survival_rate') or 0),
                        failure_mode=sr.get('failure_mode', ''),
                        recovery_path=sr.get('recovery_path', ''),
                    ))
                except (ValueError, TypeError):
                    pass  # skip malformed stress result entry
            data['stress_results'] = _stress_results
        
        # Reconstruct final_solution with ClaimLabel and MetaCognitiveAudit
        if data.get('final_solution'):
            fs = data['final_solution']
            # If it's already a FinalSolution object (unlikely here but for safety)
            if hasattr(fs, '__dataclass_fields__'):
                data['final_solution'] = fs
            else:
                # Ensure it's a dict
                fs_dict = fs if isinstance(fs, dict) else {}
                
                # Safely reconstruct meta_audit
                ma = fs_dict.get('meta_audit', {})
                if not isinstance(ma, dict): ma = {}
                meta_audit_obj = MetaCognitiveAudit(
                    most_dangerous_assumption=ma.get('most_dangerous_assumption', ''),
                    dominant_bias=ma.get('dominant_bias', ''),
                    remaining_uncertainty=ma.get('remaining_uncertainty', ''),
                    assumption_failure_impact=ma.get('assumption_failure_impact', ''),
                    non_obvious_insight=ma.get('non_obvious_insight', '')
                )
                
                # Safely reconstruct claim_labels
                raw_labels = fs_dict.get('claim_labels', {})
                if not isinstance(raw_labels, dict): raw_labels = {}
                clean_labels = {}
                for k, v in raw_labels.items():
                    try:
                        clean_labels[k] = ClaimLabel(v)
                    except ValueError:
                        clean_labels[k] = ClaimLabel.UNKNOWN

                data['final_solution'] = FinalSolution(
                    core_solution=fs_dict.get('core_solution', ''),
                    critical_insights=fs_dict.get('critical_insights', []),
                    action_blueprint=fs_dict.get('action_blueprint', []),
                    open_questions=fs_dict.get('open_questions', []),
                    claim_labels=clean_labels,
                    meta_audit=meta_audit_obj,
                    sources=fs_dict.get('sources', []),
                    generator_attribution=fs_dict.get('generator_attribution', {}),
                    critic_weighting=fs_dict.get('critic_weighting', {})
                )
        
        # Reconstruct generation_candidates
        if data.get('generation_candidates'):
            data['generation_candidates'] = [
                GenerationCandidate(**gc) for gc in data['generation_candidates']
            ]
        
        # Reconstruct critic_scores.
        # CriticDimensionScore(**v) and CriticScore(**cs) have required fields with
        # no defaults — a truncated or partially-written state file causes TypeError.
        # Build each object explicitly with .get() fallbacks and skip bad entries.
        if data.get('critic_scores'):
            new_scores = []
            for cs in data['critic_scores']:
                try:
                    safe_dim: dict[str, CriticDimensionScore] = {}
                    for k, v in cs.get('candidate_scores', {}).items():
                        try:
                            safe_dim[k] = CriticDimensionScore(
                                factuality=float(v.get('factuality') or 0),
                                reasoning=float(v.get('reasoning') or 0),
                                completeness=float(v.get('completeness') or 0),
                                helpfulness=float(v.get('helpfulness') or 0),
                            )
                        except (TypeError, ValueError):
                            pass  # skip this dimension entry
                    new_scores.append(CriticScore(
                        critic_id=cs.get('critic_id', ''),
                        critic_model=cs.get('critic_model', ''),
                        candidate_scores=safe_dim,
                        ranking=cs.get('ranking') or [],
                        dissenting_note=cs.get('dissenting_note') or '',
                    ))
                except (TypeError, ValueError, KeyError):
                    pass  # skip malformed critic score entry
            data['critic_scores'] = new_scores
        
        # Reconstruct verification_results with ClaimLabel
        if data.get('verification_results'):
            data['verification_results'] = [
                VerificationResult(
                    claim=vr['claim'],
                    source_generator=vr['source_generator'],
                    verdict=ClaimLabel(vr['verdict']),
                    evidence=vr['evidence'],
                    confidence=vr['confidence']
                ) for vr in data['verification_results']
            ]
        
        # Reconstruct meta_evaluation
        if data.get('meta_evaluation'):
            data['meta_evaluation'] = MetaEvaluation(**data['meta_evaluation'])

        # New method state dicts — safe defaults for older state files
        data.setdefault('jury_weighted_ranking', [])
        data.setdefault('pre_mortem_state', {})
        data.setdefault('bayesian_state', {})
        data.setdefault('dialectical_state', {})
        data.setdefault('analogical_state', {})
        data.setdefault('delphi_state', {})

        # Restore bounded deque for reflexion_memory
        data['reflexion_memory'] = deque(data.get('reflexion_memory', []), maxlen=50)

        return cls(**data)
