"""Preset data registry — all declarative preset configurations."""

from __future__ import annotations

from reasoner.core.constants import (
    IMAGE_GEN_BUDGET_PRESET,
    IMAGE_GEN_PREMIUM_PRESET,
    MODEL_FLUX_2_FLEX,
    MODEL_FLUX_2_PRO,
    MODEL_GEMINI_PRO_IMAGE,
)
from reasoner.domain.preset_core import PipelinePreset


# Declarative configuration for all 24 presets (2 per method).
_PRESET_CONFIGS: list[dict] = [
    # ── Multi-Perspective ───────────────────────────────────────────
    {
        "id": "multi-perspective-budget",
        "name": "Multi-Perspective (Budget)",
        "description": "Standard 6-phase pipeline using cheapest cross-lab models. DeepSeek (reasoning) + Qwen (cross-lab scoring). Pennies per run.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "mistral-large-3",
            "systemic": "gemini-flash-lite",
            "minimalist": "gemini-flash-lite",
            "scoring": "gemini-flash-lite",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-v3",
            "scoring": "glm-4-air",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek + Qwen + GLM: 3 different labs in Phase 2 = genuine diversity",
            "qwen3-turbo at ~$0.03/M is the cheapest capable model in registry",
            "Full run estimated at <$0.02 total",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "multi-perspective-premium",
        "name": "Multi-Perspective (Premium)",
        "description": "Best available model per phase. Perplexity Sonar fact-checks candidates in Phase 3. Gemini Pro and GLM-5.1 dual-check synthesis. Cross-ecosystem for maximum epistemic diversity.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "kimi-k2-6",
            "destructive": "deepseek-r1t2-chimera",
            "systemic": "qwen3.6-plus",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "qwen3.6-plus",
            "synthesis": "gemini-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "qwen3-plus",
            "systemic": "deepseek-r1",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "deepseek-r1",
            "synthesis": "mimo-v2-pro"
        },
        "notes": [
            "Phase 2: Moonshot + DeepSeek + Anthropic + Mistral — 4 different training lineages",
            "Gemini Pro: 1.6T MoE with 1M context, state-of-the-art reasoning effort.",
            "Sonar Pro in scoring phase enables live fact-checking of candidates",
            "GLM-5.1 for synthesis fallback: 200K context, 34% hallucination, 3x cheaper than GPT-5",
            "Kimi K2.6 for constructive: 1T MoE, 256K context, strongest agentic reasoning in Chinese OSS",
            "DeepSeek for destructive: 85K+ adversarial RL environments",
            "Ministral-8b for minimalist: order-of-magnitude fewer tokens by design",
            "MiMo V2 Pro for high-quality synthesis fallback."
        ],
    },

    # ── Debate ───────────────────────────────────────────────────────
    {
        "id": "debate-budget",
        "name": "Debate (Budget)",
        "description": "Adversarial debate with 3 cheap cross-lab models. DeepSeek (Model A) vs Qwen (Model B), judged by GLM. 3 different training lineages.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "gemini-flash-lite"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek + Qwen + GLM: genuine cross-lab debate",
            "Gemma 4 26B for classification: cheap but capable",
            "Estimated <$0.015 per debate run",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "debate-premium",
        "name": "Debate (Premium)",
        "description": "Elite debate. Gemini Pro vs Kimi K2.6, judged by Perplexity Sonar Pro. 3 different training paradigms + live fact-checking. GLM-5.1 synthesis fallback for low-hallucination summary.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "gemini-pro",
            "destructive": "kimi-k2-6",
            "systemic": "gemini-pro",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "gemini-pro",
            "synthesis": "gemini-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-5.1"
        },
        "notes": [
            "Gemini Pro: 1.6T MoE with 1M context, state-of-the-art reasoning effort.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude Sonnet: constitutional AI, self-critique training",
            "Kimi K2.6: 1T MoE, 256K context, strongest agentic reasoning in Chinese OSS",
            "Sonar Pro judge: live web fact-checking of both positions",
            "GLM-5.1 fallback synthesis: 200K context, low-hallucination summary.",
            "DeepSeek R1 for stress-testing: 85K+ adversarial RL environments",
        ],
    # ── Jury ─────────────────────────────────────────────────────────
    },
    {
        "id": "jury-budget",
        "name": "Jury / Orchestrated (Budget)",
        "description": "6-model jury with cheap cross-lab diversity. DeepSeek + Qwen + GLM + Gemma + Mistral + Ministral. All different labs.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "mistral-large-3",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "6 different labs = genuine epistemic diversity",
            "Ministral-8b for minimalist: order-of-magnitude fewer tokens",
            "Estimated <$0.02 per jury run",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "jury-premium",
        "name": "Jury / Orchestrated (Premium)",
        "description": "Elite 6-model jury with live fact-checking. Claude + Kimi K2.6 + DeepSeek + Gemini + Perplexity + GLM. Cross-ecosystem for maximum coverage. GLM-5.1 synthesis fallback for low-hallucination consensus.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "gemini-pro",
            "destructive": "kimi-k2-6",
            "systemic": "gemini-pro",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "gemini-pro",
            "synthesis": "qwen3.6-plus",
            "expert_1": "claude-sonnet",
            "expert_2": "kimi-k2-6",
            "expert_3": "gemini-pro",
            "expert_4": "gemini-pro",
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-5.1"
        },
        "notes": [
            "MiMo V2 Pro as primary model for strong reasoning in complex phases and an expert role.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude + Kimi + DeepSeek + Gemini + Perplexity + GLM = 6 ecosystems",
            "Sonar Pro for scoring: live web fact-checking of every candidate",
            "GLM-5.1 for synthesis fallback: 200K context, 34% hallucination, honest consensus synthesis",
        ],
    },
    # ── Research ─────────────────────────────────────────────────────
    {
        "id": "research-budget",
        "name": "Research (Budget)",
        "description": "Deep iterative search with cheap models. DeepSeek for reasoning, Qwen for synthesis, Gemma for classification.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for iterative search reasoning",
            "Qwen for synthesis: strong multilingual output",
            "Gemma for classification: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "research-premium",
        "name": "Research (Premium)",
        "description": "Elite research with live fact-checking. Claude for reasoning, Perplexity for evidence evaluation, GLM for synthesis.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "claude-sonnet",
            "destructive": "kimi-k2-6",
            "systemic": "deepseek-r1t2-chimera",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for deep reasoning and synthesis.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for deep reasoning: constitutional AI training",
            "Perplexity Sonar Pro for live evidence evaluation",
            "GLM-5 for synthesis: top of Artificial Analysis Intelligence Index",
        ],
    },
    # ── Scientific ───────────────────────────────────────────────────
    {
        "id": "scientific-budget",
        "name": "Scientific (Budget)",
        "description": "Hypothesis-test-evaluate cycle with cheap models. DeepSeek for hypothesis generation, Qwen for testing, GLM for evaluation.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for hypothesis generation: strong reasoning",
            "Qwen for testing: good at structured evaluation",
            "GLM for scoring: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "scientific-premium",
        "name": "Scientific (Premium)",
        "description": "Elite scientific reasoning. Claude for hypothesis generation, Kimi K2.6 for testing, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "claude-sonnet",
            "destructive": "kimi-k2-6",
            "systemic": "deepseek-r1t2-chimera",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for hypothesis generation and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for hypothesis generation: constitutional AI training",
            "Kimi K2.6 for testing: 1T MoE, agentic evaluation with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── Socratic ─────────────────────────────────────────────────────
    {
        "id": "socratic-budget",
        "name": "Socratic (Budget)",
        "description": "Socratic questioning with cheap models. DeepSeek for questions, Qwen for answers, GLM for evaluation.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for Socratic questions: strong reasoning",
            "Qwen for answers: good at structured response",
            "GLM for evaluation: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "socratic-premium",
        "name": "Socratic (Premium)",
        "description": "Elite Socratic dialogue. Claude for questions, Kimi K2.6 for answers, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "claude-sonnet",
            "destructive": "kimi-k2-6",
            "systemic": "deepseek-r1t2-chimera",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for Socratic questions and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for Socratic questions: constitutional AI training",
            "Kimi K2.6 for answers: 1T MoE, agentic reasoning with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── Pre-Mortem ───────────────────────────────────────────────────
    {
        "id": "pre-mortem-budget",
        "name": "Pre-Mortem (Budget)",
        "description": "Failure-mode analysis with cheap models. DeepSeek for failure scenarios, Qwen for backtracking, GLM for signals.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for failure scenarios: strong adversarial reasoning",
            "Qwen for backtracking: good at structured analysis",
            "GLM for signals: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "pre-mortem-premium",
        "name": "Pre-Mortem (Premium)",
        "description": "Elite pre-mortem analysis. Claude for failure scenarios, Kimi K2.6 for backtracking, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "claude-sonnet",
            "destructive": "kimi-k2-6",
            "systemic": "deepseek-r1t2-chimera",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for failure scenarios and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for failure scenarios: constitutional AI training",
            "Kimi K2.6 for backtracking: 1T MoE, agentic reasoning with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── Bayesian ─────────────────────────────────────────────────────
    {
        "id": "bayesian-budget",
        "name": "Bayesian (Budget)",
        "description": "Probabilistic reasoning with cheap models. DeepSeek for priors, Qwen for likelihood, GLM for posterior.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for priors: strong reasoning",
            "Qwen for likelihood: good at structured analysis",
            "GLM for posterior: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "bayesian-premium",
        "name": "Bayesian (Premium)",
        "description": "Elite Bayesian reasoning. Claude for priors, Kimi K2.6 for likelihood, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "claude-sonnet",
            "destructive": "kimi-k2-6",
            "systemic": "deepseek-r1t2-chimera",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for priors and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for priors: constitutional AI training",
            "Kimi K2.6 for likelihood: 1T MoE, agentic reasoning with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── Dialectical ──────────────────────────────────────────────────
    {
        "id": "dialectical-budget",
        "name": "Dialectical (Budget)",
        "description": "Thesis-antithesis-synthesis with cheap models. DeepSeek for thesis, Qwen for antithesis, GLM for synthesis.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for thesis: strong reasoning",
            "Qwen for antithesis: good at structured opposition",
            "GLM for synthesis: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "dialectical-premium",
        "name": "Dialectical (Premium)",
        "description": "Elite dialectical reasoning. Claude for thesis, Kimi K2.6 for antithesis, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "claude-sonnet",
            "destructive": "kimi-k2-6",
            "systemic": "deepseek-r1t2-chimera",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for thesis and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for thesis: constitutional AI training",
            "Kimi K2.6 for antithesis: 1T MoE, agentic reasoning with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── Analogical ───────────────────────────────────────────────────
    {
        "id": "analogical-budget",
        "name": "Analogical (Budget)",
        "description": "Structure-mapping and transfer with cheap models. DeepSeek for abstraction, Qwen for domain search, GLM for mapping.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for abstraction: strong reasoning",
            "Qwen for domain search: good at structured search",
            "GLM for mapping: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "analogical-premium",
        "name": "Analogical (Premium)",
        "description": "Elite analogical reasoning. Claude for abstraction, Kimi K2.6 for domain search, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "claude-sonnet",
            "destructive": "kimi-k2-6",
            "systemic": "deepseek-r1t2-chimera",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for abstraction and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for abstraction: constitutional AI training",
            "Kimi K2.6 for domain search: 1T MoE, agentic reasoning with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── Delphi ───────────────────────────────────────────────────────
    {
        "id": "delphi-budget",
        "name": "Delphi Method (Budget)",
        "description": "Structured expert consensus with cheap models. 4 cheap models (DeepSeek, Qwen, GLM, Gemma) in round-robin consensus.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max",
            "expert_1": "gemini-flash-lite",
            "expert_2": "qwen3-max",
            "expert_3": "glm-4-air",
            "expert_4": "gemini-flash-lite",
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "4 cheap models in round-robin = genuine diversity",
            "DeepSeek + Qwen + GLM + Gemma: 4 different labs",
            "Estimated <$0.03 per Delphi run",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output, including expert roles."
        ],
    },
    {
        "id": "delphi-premium",
        "name": "Delphi Method (Premium)",
        "description": "Elite Delphi consensus. 4 top models (Claude, Kimi K2.6, DeepSeek, Gemini) with Perplexity Sonar Pro for fact-checking.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "claude-sonnet",
            "destructive": "kimi-k2-6",
            "systemic": "deepseek-r1t2-chimera",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "gemini-pro",
            "expert_1": "claude-sonnet",
            "expert_2": "kimi-k2-6",
            "expert_3": "gemini-pro",
            "expert_4": "gemini-pro",
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro as primary model for strong reasoning in complex phases and an expert role.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude + Kimi K2.6 + DeepSeek + Gemini: 4 top ecosystems",
            "Perplexity Sonar Pro for fact-checking: live web verification",
            "GLM-5 for synthesis: top of Artificial Analysis Intelligence Index",
        ],
    },
    # ── CoVe ─────────────────────────────────────────────────────────
    {
        "id": "cove-budget",
        "name": "Chain-of-Verification (Budget)",
        "description": "Draft-verify-revise cycle with cheap models. DeepSeek for drafting, Qwen for verification, GLM for revision.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "cove_draft": "gemini-flash-lite",
            "cove_verify": "qwen3-max",
            "cove_answer": "glm-4-air",
            "cove_revise": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "cove_draft": "qwen3-plus",
            "cove_verify": "deepseek-v3",
            "cove_answer": "deepseek-v3",
            "cove_revise": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for drafting: strong reasoning",
            "Qwen for verification: good at structured checking",
            "GLM for revision: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "cove-premium",
        "name": "Chain-of-Verification (Premium)",
        "description": "Elite CoVe. Claude for drafting, Kimi K2.6 for verification, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "cove_draft": "claude-sonnet",
            "cove_verify": "kimi-k2-6",
            "cove_answer": "deepseek-r1t2-chimera",
            "cove_revise": "qwen3.6-plus",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "cove_draft": "qwen3-plus",
            "cove_verify": "claude-sonnet",
            "cove_answer": "qwen3-plus",
            "cove_revise": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for decomposition and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for drafting: constitutional AI training",
            "Kimi K2.6 for verification: 1T MoE, DeepSearchQA 92.5%, agentic verification with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── SoT ──────────────────────────────────────────────────────────
    {
        "id": "sot-budget",
        "name": "Skeleton-of-Thought (Budget)",
        "description": "Skeleton-then-flesh reasoning with cheap models. DeepSeek for skeleton, Qwen for solving, GLM for assembly.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "sot_skeleton": "gemini-flash-lite",
            "sot_solve": "qwen3-max",
            "sot_assemble": "glm-4-air",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "sot_skeleton": "qwen3-plus",
            "sot_solve": "deepseek-v3",
            "sot_assemble": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for skeleton: strong reasoning",
            "Qwen for solving: good at structured problem-solving",
            "GLM for assembly: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "sot-premium",
        "name": "Skeleton-of-Thought (Premium)",
        "description": "Elite SoT. Claude for skeleton, Kimi K2.6 for solving, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "sot_skeleton": "claude-sonnet",
            "sot_solve": "kimi-k2-6",
            "sot_assemble": "deepseek-r1t2-chimera",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "sot_skeleton": "qwen3-plus",
            "sot_solve": "claude-sonnet",
            "sot_assemble": "qwen3-plus",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for decomposition and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for skeleton: constitutional AI training",
            "Kimi K2.6 for solving: 1T MoE, SWE-Bench 80.2%, agentic problem solving with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── ToT ──────────────────────────────────────────────────────────
    {
        "id": "tot-budget",
        "name": "Tree-of-Thought (Budget)",
        "description": "Branching reasoning with cheap models. DeepSeek for decomposition, Qwen for generation, GLM for evaluation.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "tot_decompose": "gemini-flash-lite",
            "tot_generate": "qwen3-max",
            "tot_evaluate": "glm-4-air",
            "tot_backtrack": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "tot_decompose": "qwen3-plus",
            "tot_generate": "deepseek-v3",
            "tot_evaluate": "deepseek-v3",
            "tot_backtrack": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for decomposition: strong reasoning",
            "Qwen for generation: good at structured generation",
            "GLM for evaluation: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "tot-premium",
        "name": "Tree-of-Thought (Premium)",
        "description": "Elite ToT. Claude for decomposition, Kimi K2.6 for generation, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "tot_decompose": "claude-sonnet",
            "tot_generate": "kimi-k2-6",
            "tot_evaluate": "deepseek-r1t2-chimera",
            "tot_backtrack": "qwen3.6-plus",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "tot_decompose": "qwen3-plus",
            "tot_generate": "claude-sonnet",
            "tot_evaluate": "qwen3-plus",
            "tot_backtrack": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for decomposition and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for decomposition: constitutional AI training",
            "Kimi K2.6 for generation: 1T MoE, agentic generation with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── PoT ──────────────────────────────────────────────────────────
    {
        "id": "pot-budget",
        "name": "Program-of-Thought (Budget)",
        "description": "Code-first reasoning with cheap models. DeepSeek for generation, Qwen for execution, GLM for interpretation.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "pot_generate": "gemini-flash-lite",
            "pot_execute": "qwen3-max",
            "pot_interpret": "glm-4-air",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "pot_generate": "qwen3-plus",
            "pot_execute": "deepseek-v3",
            "pot_interpret": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for generation: strong reasoning",
            "Qwen for execution: good at structured execution",
            "GLM for interpretation: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "pot-premium",
        "name": "Program-of-Thought (Premium)",
        "description": "Elite PoT. Claude for generation, Kimi K2.6 for execution, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "pot_generate": "claude-sonnet",
            "pot_execute": "kimi-k2-6",
            "pot_interpret": "deepseek-r1t2-chimera",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "pot_generate": "qwen3-plus",
            "pot_execute": "claude-sonnet",
            "pot_interpret": "qwen3-plus",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for decomposition and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for generation: constitutional AI training",
            "Kimi K2.6 for execution: 1T MoE, SWE-Bench 80.2%, agentic code execution with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── Self-Discover ────────────────────────────────────────────────
    {
        "id": "self-discover-budget",
        "name": "Self-Discover (Budget)",
        "description": "Self-adaptive reasoning with cheap models. DeepSeek for selection, Qwen for adaptation, GLM for implementation.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "sd_select": "gemini-flash-lite",
            "sd_adapt": "qwen3-max",
            "sd_implement": "glm-4-air",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max"
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "sd_select": "qwen3-plus",
            "sd_adapt": "deepseek-v3",
            "sd_implement": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air"
        },
        "notes": [
            "DeepSeek for selection: strong reasoning",
            "Qwen for adaptation: good at structured adaptation",
            "GLM for implementation: cheap but capable",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },
    {
        "id": "self-discover-premium",
        "name": "Self-Discover (Premium)",
        "description": "Elite self-discovery. Claude for selection, Kimi K2.6 for adaptation, Perplexity for evidence evaluation.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "sd_select": "claude-sonnet",
            "sd_adapt": "kimi-k2-6",
            "sd_implement": "deepseek-r1t2-chimera",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "mimo-v2-pro"
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "sd_select": "qwen3-plus",
            "sd_adapt": "claude-sonnet",
            "sd_implement": "qwen3-plus",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5"
        },
        "notes": [
            "MiMo V2 Pro for decomposition and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "Claude for selection: constitutional AI training",
            "Kimi K2.6 for adaptation: 1T MoE, agentic adaptation with 256K context",
            "Perplexity Sonar Pro for evidence evaluation: live web fact-checking",
        ],
    },
    # ── SubAgent presets (v2.2) ──────────────────────────────────────
    # These presets are designed for the PhaseSubAgent architecture.
    # They route each subagent to a specific model with cross-lab fallbacks.
    {
        "id": "subagent-budget",
        "name": "SubAgent (Budget)",
        "description": "Per-subagent routing with cheap cross-lab models. Each subagent gets a dedicated model + fallback.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "qwen3-max",
            "systemic": "glm-4-air",
            "minimalist": "gemini-flash-lite",
            "scoring": "glm-4-air",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max",
            "subagent_synthesis_analysis": "gemini-flash-lite",
            "subagent_synthesis_writer": "qwen3-max",
            "subagent_critique_logic": "glm-4-air",
            "subagent_critique_evidence": "gemini-flash-lite",
            "subagent_critique_bias": "gemini-flash-lite",
            "subagent_critique_counter": "qwen3-max",
            "subagent_enhancement": "gemini-flash-lite",
            "subagent_decomposition": "gemini-flash-lite",
            "subagent_search_query": "qwen3-max",
            "subagent_search_eval": "glm-4-air",
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "deepseek-v3",
            "minimalist": "deepseek-v3",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air",
            "subagent_synthesis_analysis": "qwen3-plus",
            "subagent_synthesis_writer": "deepseek-v3",
            "subagent_critique_logic": "deepseek-v3",
            "subagent_critique_evidence": "glm-4-air",
            "subagent_critique_bias": "qwen3-plus",
            "subagent_critique_counter": "deepseek-v3",
            "subagent_enhancement": "glm-4-air",
            "subagent_decomposition": "glm-4-air",
            "subagent_search_query": "deepseek-v3",
            "subagent_search_eval": "qwen3-plus",
        },
        "notes": [
            "Every subagent has a cross-lab fallback (different provider)",
            "DeepSeek + Qwen + GLM + Gemma: 4 different labs",
            "Estimated <$0.02 per subagent run",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output in subagent roles."
        ],
    },
    {
        "id": "subagent-premium",
        "name": "SubAgent (Premium)",
        "description": "Elite per-subagent routing with top models. Each subagent gets a dedicated top model + fallback.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "claude-sonnet",
            "destructive": "kimi-k2-6",
            "systemic": "deepseek-r1t2-chimera",
            "minimalist": "gemini-flash",
            "scoring": "sonar-pro",
            "stress_testing": "deepseek-r1t2-chimera",
            "synthesis": "gemini-pro",
            "subagent_synthesis_analysis": "deepseek-r1t2-chimera",
            "subagent_synthesis_writer": "claude-sonnet",
            "subagent_critique_logic": "gemini-pro",
            "subagent_critique_evidence": "sonar-pro",
            "subagent_critique_bias": "deepseek-r1t2-chimera",
            "subagent_critique_counter": "claude-sonnet",
            "subagent_enhancement": "gemini-pro",
            "subagent_decomposition": "deepseek-r1t2-chimera",
            "subagent_search_query": "gemini-pro",
            "subagent_search_eval": "claude-sonnet",
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "deepseek-r1",
            "decomposition": "gemini-flash",
            "constructive": "qwen3-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-r1",
            "scoring": "qwen3-plus",
            "stress_testing": "qwen3-plus",
            "synthesis": "gpt-5",
            "subagent_synthesis_analysis": "qwen3-plus",
            "subagent_synthesis_writer": "deepseek-r1",
            "subagent_critique_logic": "deepseek-r1",
            "subagent_critique_evidence": "qwen3-plus",
            "subagent_critique_bias": "qwen3-plus",
            "subagent_critique_counter": "deepseek-r1",
            "subagent_enhancement": "deepseek-r1",
            "subagent_decomposition": "qwen3-plus",
            "subagent_search_query": "deepseek-r1",
            "subagent_search_eval": "qwen3-plus",
        },
        "notes": [
            "Gemini Pro: 1.6T MoE with 1M context, state-of-the-art reasoning effort.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "SubAgent overhead: ~11.5 cents per run vs monolithic",
            "No Qwen 3.6 Plus — Sonnet handles writer tasks at 60% lower cost",
            "Gemini Flash for all parallel analysis: fast, cheap, high throughput",
            "DeepSeek R1 for reasoning tasks: 85K+ adversarial RL environments",
            "Sonar Pro for evidence/source evaluation: live web fact-checking",
            "Every subagent has cross-lab fallback (different provider)",
        ],
    },
    # ── Writing (Research-Backed Article) ────────────────────────────
    {
        "id": "writing-budget",
        "name": "Writing / Article (Budget)",
        "description": "Research-backed article generation with CoVE, Pre-Mortem, and SoT using cheap cross-lab models. DeepSeek decomposes + CoVE verifies, Mistral extracts, Kimi K2.6 synthesizes via SoT, DeepSeek-R1 criticizes with Pre-Mortem. Estimated <$0.05 per article.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "article_decompose": "gemini-flash-lite",
            "article_claim_extract": "mistral-large-3",
            "article_cove_verify": "deepseek-r1t2-chimera",
            "article_cove_answer": "gemini-flash-lite",
            "article_cove_revise": "gemini-flash-lite",
            "article_verifier": "gemini-flash-lite",
            "article_sot_skeleton": "gemini-flash-lite",
            "article_sot_solve": "kimi-k2-6",
            "article_synthesize": "kimi-k2-6",
            "article_pre_mortem": "gemini-flash-lite",
            "article_critic": "gemini-flash-lite",
            "article_assemble": "kimi-k2-6",
        },
        "fallback_routing": {
            "article_decompose": "glm-4-air",
            "article_claim_extract": "deepseek-v3",
            "article_cove_verify": "mistral-large-3",
            "article_cove_answer": "glm-4-air",
            "article_cove_revise": "glm-4-air",
            "article_verifier": "mistral-large-3",
            "article_sot_skeleton": "glm-4-air",
            "article_sot_solve": "deepseek-v3",
            "article_synthesize": "deepseek-v3",
            "article_pre_mortem": "mistral-large-3",
            "article_critic": "mistral-large-3",
            "article_assemble": "deepseek-v3",
        },
        "notes": [
            "DeepSeek V3: decomposition, CoVE answer/revise, SoT skeleton — fast structured output",
            "DeepSeek R1: CoVE verify, adversarial verifier, pre-mortem, critic — reasoning model",
            "Mistral Large 3: claim extraction — high precision on factual text",
            "Kimi K2.6: SoT section writing, synthesis, assembly — 1T MoE, 256K context, agentic writing at $2.10/M",
            "GLM-4-Air: universal fallback — cheapest capable model if primary fails",
            "Gemini Flash Lite: reliable JSON and instruction-following for article generation phases."
        ],
    },
    {
        "id": "writing-premium",
        "name": "Writing / Article (Premium)",
        "description": "Elite article generation with CoVE, Pre-Mortem, and SoT. Claude Sonnet handles decomposition, CoVE, and verification. GLM-5.1 synthesizes, critiques, and assembles with 200K context and 34% hallucination rate. Estimated $0.15-0.20 per article.",
        "primary_id": "gemini-pro",
        "routing": {
            "article_decompose": "mimo-v2-flash",
            "article_claim_extract": "claude-sonnet",
            "article_cove_verify": "claude-sonnet",
            "article_cove_answer": "claude-sonnet",
            "article_cove_revise": "claude-sonnet",
            "article_verifier": "claude-sonnet",
            "article_sot_skeleton": "claude-sonnet",
            "article_sot_solve": "glm-5.1",
            "article_synthesize": "gemini-pro",
            "article_pre_mortem": "gemini-pro",
            "article_critic": "gemini-pro",
            "article_assemble": "glm-5.1",
        },
        "fallback_routing": {
            "article_decompose": "gpt-5",
            "article_claim_extract": "gpt-5",
            "article_cove_verify": "gpt-5",
            "article_cove_answer": "gpt-5",
            "article_cove_revise": "gpt-5",
            "article_verifier": "grok-4.20",
            "article_sot_skeleton": "gpt-5",
            "article_sot_solve": "claude-sonnet",
            "article_synthesize": "claude-sonnet",
            "article_pre_mortem": "claude-sonnet",
            "article_critic": "claude-sonnet",
            "article_assemble": "claude-sonnet",
        },
        "notes": [
            "MiMo V2 Pro for decomposition, synthesis, pre-mortem, and critique.",
            "MiMo V2 Flash for efficient early-phase article decomposition.",
            "Claude Sonnet: decomposition, claim extract, CoVE all steps, verification — best reasoning",
            "GLM-5.1: SoT section writing, synthesis, assembly, pre-mortem, critic — 200K context, 34% hallucination rate, SWE-bench 77.8%, honest self-criticism",
            "Grok 4.20: fallback for hostile review — xAI adversarial training excels at contradiction detection",
            "Every phase has cross-provider fallback (Anthropic ↔ OpenAI ↔ xAI)",
            "Critical bottleneck (CoVE verify + verifier): Claude's constitutional AI for contradiction detection",
        ],
    },
    # ── Cross-Language ───────────────────────────────────────────────
    {
        "id": "cross-language-budget",
        "name": "Cross-Language (Budget)",
        "description": "Multi-perspective reasoning with DeepL translation. Non-English problems are translated to English for reasoning, then the synthesis is translated back to the source language. Uses cheapest cross-lab models.",
        "primary_id": "gemini-flash-lite",
        "routing": {
            "prompt_enhancement": "gemini-flash-lite",
            "classification": "gpt-4o-mini",
            "decomposition": "gemini-flash-lite",
            "constructive": "gemini-flash-lite",
            "destructive": "mistral-large-3",
            "systemic": "gemini-flash-lite",
            "minimalist": "gemini-flash-lite",
            "scoring": "gemini-flash-lite",
            "stress_testing": "gemini-flash-lite",
            "synthesis": "qwen3-max",
        },
        "fallback_routing": {
            "prompt_enhancement": "glm-4-air",
            "classification": "glm-4-air",
            "decomposition": "glm-4-air",
            "constructive": "qwen3-plus",
            "destructive": "deepseek-v3",
            "systemic": "qwen3-plus",
            "minimalist": "deepseek-v3",
            "scoring": "glm-4-air",
            "stress_testing": "qwen3-plus",
            "synthesis": "glm-4-air",
        },
        "required_env_vars": ["OPENROUTER_API_KEY", "DEEPL_API_KEY"],
        "notes": [
            "DeepL free tier: 500K chars/month — sufficient for most use cases",
            "DeepL paid tier: 50M chars/month with next-gen model support",
            "Translation preserves formatting and line breaks",
            "Same cross-lab diversity as multi-perspective budget",
            "Gemini Flash Lite: low-cost primary workhorse with reliable JSON output across all structural phases."
        ],
    },

    {
        "id": "cross-language-premium",
        "name": "Cross-Language (Premium)",
        "description": "Best available multi-perspective reasoning with DeepL translation. Non-English problems are translated to English for reasoning, then the synthesis is translated back with the highest-quality models.",
        "primary_id": "gemini-pro",
        "routing": {
            "prompt_enhancement": "mimo-v2-flash",
            "classification": "mimo-v2-flash",
            "decomposition": "gemini-pro",
            "constructive": "qwen3.6-plus",
            "destructive": "claude-sonnet",
            "systemic": "qwen3.6-plus",
            "minimalist": "gemini-pro",
            "scoring": "qwen3.6-plus",
            "stress_testing": "qwen3.6-plus",
            "synthesis": "gemini-pro",
        },
        "fallback_routing": {
            "prompt_enhancement": "claude-sonnet",
            "classification": "claude-sonnet",
            "decomposition": "claude-sonnet",
            "constructive": "claude-sonnet",
            "destructive": "gemini-pro",
            "systemic": "claude-sonnet",
            "minimalist": "claude-sonnet",
            "scoring": "claude-sonnet",
            "stress_testing": "claude-sonnet",
            "synthesis": "claude-sonnet",
        },
        "required_env_vars": ["OPENROUTER_API_KEY", "DEEPL_API_KEY"],
        "notes": [
            "MiMo V2 Pro for decomposition and synthesis: strong reasoning capabilities.",
            "MiMo V2 Flash for efficient early-phase prompt enhancement and classification.",
            "DeepL paid tier recommended for high-volume usage",
            "Perplexity Sonar fact-checks candidates in Phase 3 (if enabled)",
            "Qwen 3.6 Plus and GLM-5.1 dual-check synthesis",
            "Cross-ecosystem for maximum epistemic diversity",
        ],
    },
    # ── NVIDIA NIM (Experimental) ────────────────────────────────────
    {
        "id": "nvidia-nemotron-test",
        "name": "NVIDIA Nemotron (Test)",
        "description": "Experimental preset using NVIDIA Nemotron-3-Super-120B-A12B via NIM free tier. Designed for --sequential mode to stay within 40 RPM limit. NOT for production use.",
        "primary_id": "nvidia-nemotron-super",
        "routing": {
            "prompt_enhancement": "nvidia-nemotron-super",
            "classification": "nvidia-nemotron-super",
            "decomposition": "nvidia-nemotron-super",
            "constructive": "nvidia-nemotron-super",
            "destructive": "nvidia-nemotron-super",
            "systemic": "nvidia-nemotron-super",
            "minimalist": "nvidia-nemotron-super",
            "scoring": "nvidia-nemotron-super",
            "stress_testing": "nvidia-nemotron-super",
            "synthesis": "nvidia-nemotron-super",
        },
        "fallback_routing": {
            "prompt_enhancement": "gemma-4-26b",
            "classification": "gemma-4-26b",
            "decomposition": "deepseek-v3",
            "constructive": "deepseek-v3",
            "destructive": "mistral-large-3",
            "systemic": "deepseek-v3",
            "minimalist": "gemma-4-26b",
            "scoring": "glm-4-air",
            "stress_testing": "deepseek-v3",
            "synthesis": "qwen3-max",
        },
        "required_env_vars": ["NVIDIA_API_KEY"],
        "notes": [
            "NVIDIA NIM free tier: 1,000 credits, 40 RPM hard cap",
            "Use ONLY with --sequential flag: python main.py --preset nvidia-nemotron-test --sequential",
            "Parallel mode will hit 429 rate limit errors instantly",
            "Nemotron-3-Super: 120B MoE / 12B active. NVIDIA-developed model — new lab diversity",
            "Fallback chain uses OpenRouter models if NVIDIA API fails",
        ],
    },
    # ── Image Generation ─────────────────────────────────────────────
    {
        "id": IMAGE_GEN_BUDGET_PRESET,
        "name": "Image Generation (Budget)",
        "description": "Generate images using Flux 2 Flex and Riverflow v2 Fast Preview as primary models, with Seedream 4.5, Flux 2 Pro, and Riverflow v2 Standard Preview as fallbacks.",
        "primary_id": MODEL_FLUX_2_FLEX,
        "routing": {},
        "fallback_routing": {},
        "notes": [
            "Flux 2 Flex: efficient open‑source image model, fast and cost‑effective",
            "Riverflow v2 Fast Preview: optimized for speed with good quality",
            "Seedream 4.5 fallback: ByteDance's capable image model",
            "Flux 2 Pro fallback: higher quality with more detail",
            "Riverflow v2 Standard Preview fallback: balanced quality and speed",
        ],
    },
    {
        "id": IMAGE_GEN_PREMIUM_PRESET,
        "name": "Image Generation (Premium)",
        "description": "Generate images using Flux 2 Pro and Riverflow v2 Pro as primary models, with Flux 2 Max, Riverflow v2 Max Preview, and Seedream 4.5 as fallbacks.",
        "primary_id": MODEL_GEMINI_PRO_IMAGE,
        "routing": {},
        "fallback_routing": {},
        "notes": [
            "Gemini 3 Pro Image Preview: $2/M input, $12/M output — best text-in-image, 2K/4K support",
            "GPT-5 Image fallback: OpenAI flagship with excellent instruction following",
            "Gemini 3.1 Flash Image Preview final fallback: fast high-quality safety net",
        ],
    },
]


PRESETS: dict[str, PipelinePreset] = {
    cfg["id"]: PipelinePreset(
        name=cfg["name"],
        description=cfg["description"],
        primary_id=cfg["primary_id"],
        routing=cfg.get("routing", {}),
        notes=cfg.get("notes", []),
        required_env_vars=cfg.get("required_env_vars", ["OPENROUTER_API_KEY"]),
        fallback_routing=cfg.get("fallback_routing", {}),
    )
    for cfg in _PRESET_CONFIGS
}
